CREATE TABLE IF NOT EXISTS videos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    uploaded_by INT NOT NULL,
    s3_key VARCHAR(500) NOT NULL,
    s3_url VARCHAR(1000) NOT NULL,
    original_filename VARCHAR(255),
    file_size BIGINT,
    duration INT,
    mime_type VARCHAR(100),
    upload_type ENUM('file', 'link') NOT NULL,
    original_url VARCHAR(1000),
    compression_status ENUM('pending', 'processing', 'completed', 'failed') DEFAULT 'pending',
    transcription_status ENUM('pending', 'processing', 'completed', 'failed') DEFAULT 'pending',
    summary_status ENUM('pending', 'processing', 'completed', 'failed') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_uploaded_by (uploaded_by),
    INDEX idx_created_at (created_at),
    INDEX idx_transcription_status (transcription_status),
    INDEX idx_summary_status (summary_status)
);
